
production: true

title: Emanuel Kluge
description: Beitr√§ge zum Thema JS, HTML, CSS & anderem Kram
baseurl: ""
url: http://www.emanuel-kluge.de/
twitter_username: herschel_r
github_username:  herschel666
google_plus: EmanuelKluge
markdown: redcarpet
default_locale: "de"
paginate: 10
paginate_path: "/page/:num/"
lsi: false
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/styles
  js_compressor: yui
  css_compressor: sass
  gzip: ['text/css']

gems:
  - jekyll-assets
  - jekyll-minifier

jekyll-minifier:
  exclude: ['node_modules', '_assets']

ftp_host: 'emanuel-kluge.de'
ftp_dir: '/'
ftp_passive: false

include: ['.htaccess']
exclude: [
  '_assets',
  '_posts.bak',
  'bower.json',
  'package.json',
  'Gemfile',
  'Gemfile.lock',
  'Gruntfile.coffee',
  'userfiles',
  'node_modules'
]
